//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ContextBanca : DbContext
    {
        public ContextBanca()
            : base("name=ContextBanca")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBL_CALLCENTER_REGISTRO_REPORTE> TBL_CALLCENTER_REGISTRO_REPORTE { get; set; }
        public DbSet<CAT_CALLCENTER_ACCIONES_CAUSA> CAT_CALLCENTER_ACCIONES_CAUSA { get; set; }
        public DbSet<CAT_CALLCENTER_MEDIO_MOVIMIENTO> CAT_CALLCENTER_MEDIO_MOVIMIENTO { get; set; }
        public DbSet<TBL_BANCA_SOCIOS> TBL_BANCA_SOCIOS { get; set; }
        public DbSet<CAT_CALLCENTER_TIPO_CUENTA_NO_AFECTADA> CAT_CALLCENTER_TIPO_CUENTA_NO_AFECTADA { get; set; }
    
        public virtual ObjectResult<SP_CALLCENTER_INSERTAR_REGISTRO_REPORTE_Result> SP_CALLCENTER_INSERTAR_REGISTRO_REPORTE(Nullable<long> numero_Socio, Nullable<long> iD_SUPUESTOS_REPORTE, string detalles_llamada, string numero_usuario, Nullable<int> id_tipo_bitacora)
        {
            var numero_SocioParameter = numero_Socio.HasValue ?
                new ObjectParameter("numero_Socio", numero_Socio) :
                new ObjectParameter("numero_Socio", typeof(long));
    
            var iD_SUPUESTOS_REPORTEParameter = iD_SUPUESTOS_REPORTE.HasValue ?
                new ObjectParameter("ID_SUPUESTOS_REPORTE", iD_SUPUESTOS_REPORTE) :
                new ObjectParameter("ID_SUPUESTOS_REPORTE", typeof(long));
    
            var detalles_llamadaParameter = detalles_llamada != null ?
                new ObjectParameter("detalles_llamada", detalles_llamada) :
                new ObjectParameter("detalles_llamada", typeof(string));
    
            var numero_usuarioParameter = numero_usuario != null ?
                new ObjectParameter("numero_usuario", numero_usuario) :
                new ObjectParameter("numero_usuario", typeof(string));
    
            var id_tipo_bitacoraParameter = id_tipo_bitacora.HasValue ?
                new ObjectParameter("id_tipo_bitacora", id_tipo_bitacora) :
                new ObjectParameter("id_tipo_bitacora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CALLCENTER_INSERTAR_REGISTRO_REPORTE_Result>("SP_CALLCENTER_INSERTAR_REGISTRO_REPORTE", numero_SocioParameter, iD_SUPUESTOS_REPORTEParameter, detalles_llamadaParameter, numero_usuarioParameter, id_tipo_bitacoraParameter);
        }
    
        public virtual int SP_BANCA_OBTENER_NOTIFICACION_CORREO(Nullable<int> id_notificacion_correo, Nullable<int> numero, Nullable<int> num_usuario)
        {
            var id_notificacion_correoParameter = id_notificacion_correo.HasValue ?
                new ObjectParameter("id_notificacion_correo", id_notificacion_correo) :
                new ObjectParameter("id_notificacion_correo", typeof(int));
    
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            var num_usuarioParameter = num_usuario.HasValue ?
                new ObjectParameter("num_usuario", num_usuario) :
                new ObjectParameter("num_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BANCA_OBTENER_NOTIFICACION_CORREO", id_notificacion_correoParameter, numeroParameter, num_usuarioParameter);
        }
    
        public virtual ObjectResult<SP_CALLCENTER_OBTENER_MEDIO_MOVIMIENTO_Result> SP_CALLCENTER_OBTENER_MEDIO_MOVIMIENTO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CALLCENTER_OBTENER_MEDIO_MOVIMIENTO_Result>("SP_CALLCENTER_OBTENER_MEDIO_MOVIMIENTO");
        }
    
        public virtual ObjectResult<SP_BANCA_OBTENER_MONTO_MAXIMO_Result> SP_BANCA_OBTENER_MONTO_MAXIMO(Nullable<int> idLimiteTransferencia)
        {
            var idLimiteTransferenciaParameter = idLimiteTransferencia.HasValue ?
                new ObjectParameter("idLimiteTransferencia", idLimiteTransferencia) :
                new ObjectParameter("idLimiteTransferencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BANCA_OBTENER_MONTO_MAXIMO_Result>("SP_BANCA_OBTENER_MONTO_MAXIMO", idLimiteTransferenciaParameter);
        }
    
        public virtual ObjectResult<SP_BANCA_BLOQUEAR_SOCIO_Result> SP_BANCA_BLOQUEAR_SOCIO(Nullable<int> numero_Socio, Nullable<int> tipo_origen, string numero_usuario, string descripcion_bloqueo, Nullable<int> id_tipo_bitacora, Nullable<int> id_motivo_bloqueo)
        {
            var numero_SocioParameter = numero_Socio.HasValue ?
                new ObjectParameter("numero_Socio", numero_Socio) :
                new ObjectParameter("numero_Socio", typeof(int));
    
            var tipo_origenParameter = tipo_origen.HasValue ?
                new ObjectParameter("tipo_origen", tipo_origen) :
                new ObjectParameter("tipo_origen", typeof(int));
    
            var numero_usuarioParameter = numero_usuario != null ?
                new ObjectParameter("numero_usuario", numero_usuario) :
                new ObjectParameter("numero_usuario", typeof(string));
    
            var descripcion_bloqueoParameter = descripcion_bloqueo != null ?
                new ObjectParameter("descripcion_bloqueo", descripcion_bloqueo) :
                new ObjectParameter("descripcion_bloqueo", typeof(string));
    
            var id_tipo_bitacoraParameter = id_tipo_bitacora.HasValue ?
                new ObjectParameter("id_tipo_bitacora", id_tipo_bitacora) :
                new ObjectParameter("id_tipo_bitacora", typeof(int));
    
            var id_motivo_bloqueoParameter = id_motivo_bloqueo.HasValue ?
                new ObjectParameter("id_motivo_bloqueo", id_motivo_bloqueo) :
                new ObjectParameter("id_motivo_bloqueo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BANCA_BLOQUEAR_SOCIO_Result>("SP_BANCA_BLOQUEAR_SOCIO", numero_SocioParameter, tipo_origenParameter, numero_usuarioParameter, descripcion_bloqueoParameter, id_tipo_bitacoraParameter, id_motivo_bloqueoParameter);
        }
    
        public virtual ObjectResult<SP_BANCA_MODIFICAR_MONTO_MAXIMO_Result> SP_BANCA_MODIFICAR_MONTO_MAXIMO(Nullable<int> numero_Socio, Nullable<int> tipo_origen, string numero_usuario, Nullable<decimal> monto_maximo_transferencia)
        {
            var numero_SocioParameter = numero_Socio.HasValue ?
                new ObjectParameter("numero_Socio", numero_Socio) :
                new ObjectParameter("numero_Socio", typeof(int));
    
            var tipo_origenParameter = tipo_origen.HasValue ?
                new ObjectParameter("tipo_origen", tipo_origen) :
                new ObjectParameter("tipo_origen", typeof(int));
    
            var numero_usuarioParameter = numero_usuario != null ?
                new ObjectParameter("numero_usuario", numero_usuario) :
                new ObjectParameter("numero_usuario", typeof(string));
    
            var monto_maximo_transferenciaParameter = monto_maximo_transferencia.HasValue ?
                new ObjectParameter("monto_maximo_transferencia", monto_maximo_transferencia) :
                new ObjectParameter("monto_maximo_transferencia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BANCA_MODIFICAR_MONTO_MAXIMO_Result>("SP_BANCA_MODIFICAR_MONTO_MAXIMO", numero_SocioParameter, tipo_origenParameter, numero_usuarioParameter, monto_maximo_transferenciaParameter);
        }
    }
}
