//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_UNE_CUENTAS
    {
        public CAT_UNE_CUENTAS()
        {
            this.TBL_UNE_REPORTE = new HashSet<TBL_UNE_REPORTE>();
            this.CAT_UNE_SUPUESTOS_REPORTE = new HashSet<CAT_UNE_SUPUESTOS_REPORTE>();
        }
    
        public int ID_CUENTA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> ID_TIPO_CUENTA { get; set; }
        public Nullable<int> ID_MOV_HAPE { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
    
        public virtual ICollection<TBL_UNE_REPORTE> TBL_UNE_REPORTE { get; set; }
        public virtual CAT_UNE_TIPO_CUENTA CAT_UNE_TIPO_CUENTA { get; set; }
        public virtual ICollection<CAT_UNE_SUPUESTOS_REPORTE> CAT_UNE_SUPUESTOS_REPORTE { get; set; }
    }
}
