//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_UNE_SUPUESTOS_REPORTE
    {
        public int ID_SUPUESTOS_REPORTE { get; set; }
        public Nullable<int> ID_TIPO_REPORTE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> DIAS_REQUERIDOS { get; set; }
        public Nullable<int> ID_TIPO_CUENTA { get; set; }
        public Nullable<int> ID_CUENTA { get; set; }
        public Nullable<int> ACTIVO { get; set; }
        public Nullable<int> VALIDA_IMPORTE_RECLAMACION { get; set; }
        public Nullable<bool> requiere_autentificacion { get; set; }
        public Nullable<int> id_accion_causa { get; set; }
        public Nullable<int> ID_CANAL { get; set; }
        public Nullable<int> ID_MOTIVO_CANCELACION { get; set; }
    
        public virtual CAT_UNE_TIPO_REPORTE CAT_UNE_TIPO_REPORTE { get; set; }
        public virtual CAT_UNE_CUENTAS CAT_UNE_CUENTAS { get; set; }
        public virtual CAT_UNE_TIPO_CUENTA CAT_UNE_TIPO_CUENTA { get; set; }
    }
}
