//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_UNE_FINALIZADO_DEBITO
    {
        public int ID_FINALIZADO_DEBITO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual CAT_UNE_FINALIZADO_DEBITO CAT_UNE_FINALIZADO_DEBITO1 { get; set; }
        public virtual CAT_UNE_FINALIZADO_DEBITO CAT_UNE_FINALIZADO_DEBITO2 { get; set; }
    }
}
