//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLAVES
    {
        public int Numusuario { get; set; }
        public string Usuario { get; set; }
        public int Numemp { get; set; }
        public int autorizo { get; set; }
        public string Correo { get; set; }
        public string Nombre_s { get; set; }
        public string Apellido_paterno { get; set; }
        public string Apellido_materno { get; set; }
        public System.DateTime Fecha_Cambio_Contrasena { get; set; }
        public int Id_de_sucursal { get; set; }
        public string Cierre { get; set; }
        public string Cta_Deud { get; set; }
        public string Permisos { get; set; }
        public string Permisos_Respaldo { get; set; }
        public int Id_area { get; set; }
        public string Nota_Cal { get; set; }
        public string Aviso1_Cal { get; set; }
        public string Aviso2_Cal { get; set; }
        public string Aviso1_Estado { get; set; }
        public string Aviso2_Estado { get; set; }
        public string Leyenda_Ficha { get; set; }
        public string Contrasena { get; set; }
        public string Nom_Maquina { get; set; }
        public string Gafete_Impreso { get; set; }
        public Nullable<System.DateTime> Gafete_Fecha { get; set; }
        public string NSS { get; set; }
        public Nullable<short> Id_ccostos_nomina { get; set; }
        public Nullable<int> Id_GeneroWoccu { get; set; }
        public string Correo_externo { get; set; }
        public string Permisos_CYC { get; set; }
        public Nullable<int> Id_Dpto { get; set; }
        public Nullable<int> Id_Rol { get; set; }
        public int Id_bloqueo { get; set; }
        public string Objetivo { get; set; }
        public Nullable<int> Numusuario_Jefe { get; set; }
        public Nullable<int> Id_Ticket { get; set; }
        public Nullable<int> Id_Proceso { get; set; }
        public Nullable<int> Id_Accion { get; set; }
        public Nullable<int> Comodin { get; set; }
    }
}
