//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMV_REC_DATA
    {
        public int ID_TBL_INT { get; set; }
        public Nullable<decimal> INB_OUT_ID { get; set; }
        public Nullable<decimal> CALLTYPE { get; set; }
        public string CRM_FOLIO { get; set; }
        public Nullable<System.DateTime> RDATE { get; set; }
        public string PATH_REC { get; set; }
        public string CALL_ID { get; set; }
        public string PHONE { get; set; }
        public Nullable<decimal> P_STATUS { get; set; }
    }
}
