//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SICORP_ROLES
    {
        public int Id_Rol { get; set; }
        public string Nom_Rol { get; set; }
        public int Id_Dpto { get; set; }
        public Nullable<int> Id_tipo_jefe { get; set; }
        public Nullable<bool> activo { get; set; }
        public string nomenclatura { get; set; }
        public Nullable<int> Id_Nivel_de_Rol { get; set; }
    }
}
