//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UNE_REPORTE
    {
        public TBL_UNE_REPORTE()
        {
            this.TBL_UNE_CANALIZACIONES = new HashSet<TBL_UNE_CANALIZACIONES>();
            this.TBL_UNE_USUARIOS_ASIGNADOS = new HashSet<TBL_UNE_USUARIOS_ASIGNADOS>();
        }
    
        public int FOLIO { get; set; }
        public Nullable<int> ES_SOCIO { get; set; }
        public Nullable<int> NUMERO { get; set; }
        public string NOMBRE_S { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string TELEFONO { get; set; }
        public string TEL_CELULAR { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public Nullable<int> USUARIO_REGISTRA { get; set; }
        public Nullable<int> ID_DE_SUCURSAL { get; set; }
        public string DESCRIPCION_REPORTE { get; set; }
        public Nullable<int> ID_TIPO_REPORTE { get; set; }
        public Nullable<int> ID_SUPUESTOS_REPORTE { get; set; }
        public Nullable<int> ID_MEDIO_CONTACTO { get; set; }
        public Nullable<int> ID_ESTATUS_REPORTE { get; set; }
        public Nullable<System.DateTime> Fecha_cierre { get; set; }
        public string Observaciones_cierre { get; set; }
        public Nullable<int> ENTIDAD { get; set; }
        public Nullable<decimal> IMPORTE_RECLAMACION { get; set; }
        public Nullable<decimal> IMPORTE_SOLUCION { get; set; }
        public Nullable<int> ID_TIPO_CUENTA { get; set; }
        public Nullable<int> ID_CUENTA { get; set; }
        public Nullable<int> ID_SATISFACTORIO { get; set; }
        public Nullable<int> ID_SUCURSAL_REGISTRO { get; set; }
        public string Comentarios_cancelacion { get; set; }
        public Nullable<System.DateTime> FECHA_Canalizacion { get; set; }
        public Nullable<int> NUM_FOLIO { get; set; }
        public Nullable<int> DIAS_RESTANTES_GENERAL { get; set; }
        public Nullable<int> DIAS_RESTANTES_AREA_ESPECIALIZADA { get; set; }
        public Nullable<int> VoBo { get; set; }
        public Nullable<int> Vencido { get; set; }
        public string Num_Tarjeta { get; set; }
        public Nullable<int> ID_PROCEDE_DEBITO { get; set; }
        public Nullable<int> BANDEJA_DEBITO { get; set; }
        public Nullable<int> ID_FINALIZADO_DEBITO { get; set; }
        public string DOMICILIO { get; set; }
        public string NUMERO_DE_REFERENCIA { get; set; }
        public Nullable<int> ID_PROCEDE_CORRESPONSALIAS { get; set; }
        public bool REPORTE_CORRESPONSALIAS { get; set; }
        public Nullable<System.DateTime> FECHA_SOLICITUD_ACLARACION { get; set; }
        public Nullable<System.DateTime> FECHA_TRANSACCION { get; set; }
        public Nullable<int> folio_banca { get; set; }
        public Nullable<int> id_medio_deteccion_movimiento { get; set; }
        public Nullable<int> folio_autorizacion_banca { get; set; }
        public Nullable<bool> reporte_banca { get; set; }
        public Nullable<int> id_tipo_cuenta_banca { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<int> ID_CANAL { get; set; }
        public Nullable<int> ID_MOTIVO_CANCELACION { get; set; }
        public Nullable<int> ID_RESOLUCION { get; set; }
        public Nullable<int> ID_CAUSA_RESOLUCION { get; set; }
        public string NUMERO_CUENTA_PTMO { get; set; }
        public Nullable<System.DateTime> FECHA_ABONO { get; set; }
        public Nullable<System.DateTime> fecha_compromiso_reporte { get; set; }
        public Nullable<int> id_cuenta_no_afectada_banca { get; set; }
    
        public virtual CAT_UNE_ESTATUS_REPORTE CAT_UNE_ESTATUS_REPORTE { get; set; }
        public virtual CAT_UNE_MEDIO_CONTACTO CAT_UNE_MEDIO_CONTACTO { get; set; }
        public virtual CAT_UNE_TIPO_REPORTE CAT_UNE_TIPO_REPORTE { get; set; }
        public virtual ICollection<TBL_UNE_CANALIZACIONES> TBL_UNE_CANALIZACIONES { get; set; }
        public virtual ICollection<TBL_UNE_USUARIOS_ASIGNADOS> TBL_UNE_USUARIOS_ASIGNADOS { get; set; }
        public virtual CAT_UNE_CUENTAS CAT_UNE_CUENTAS { get; set; }
        public virtual CAT_UNE_TIPO_CUENTA CAT_UNE_TIPO_CUENTA { get; set; }
        public virtual CAT_UNE_PROCEDE_DEBITO CAT_UNE_PROCEDE_DEBITO { get; set; }
        public virtual CAT_UNE_PROCEDE_CORRESPONSALIAS CAT_UNE_PROCEDE_CORRESPONSALIAS { get; set; }
    }
}
