//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UNE_CANALIZACIONES
    {
        public int ID_CANALIZACION { get; set; }
        public Nullable<int> FOLIO { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public string COMENTARIOS { get; set; }
        public Nullable<int> numusuario { get; set; }
        public Nullable<int> ID_TIPO_COMENTARIO { get; set; }
    
        public virtual TBL_UNE_REPORTE TBL_UNE_REPORTE { get; set; }
    }
}
