//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UNE_PERMISOS_ADMIN
    {
        public int CONTADOR { get; set; }
        public Nullable<int> ID_ROL { get; set; }
        public string NOM_ROL { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public Nullable<int> ACTIVO { get; set; }
        public Nullable<int> PERMISO_CONDUSEF { get; set; }
        public Nullable<int> USUARIO_UNE { get; set; }
        public Nullable<int> PERMISO_REGISTRAR { get; set; }
        public Nullable<int> PERMISO_DEBITO { get; set; }
        public Nullable<int> PERMISO_OPERAR_DETALLE { get; set; }
        public Nullable<bool> USUARIO_CALL_CENTER { get; set; }
        public Nullable<bool> ADMINISTRADOR_CALL_CENTER { get; set; }
        public Nullable<bool> USUARIO_SUCURSAL { get; set; }
    }
}
