//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UNE_PIVOTE_REPORTE
    {
        public int PIVOTE { get; set; }
        public Nullable<int> CONTADOR { get; set; }
        public Nullable<int> NUMUSUARIO_REPORTE { get; set; }
        public Nullable<int> FOLIO { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public Nullable<int> ES_SOCIO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> NUMERO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTATUS { get; set; }
        public string SUBESTATUS { get; set; }
        public Nullable<int> NUMUSUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_RESOLUCION { get; set; }
        public Nullable<System.DateTime> FECHA_NOTIFICACION { get; set; }
        public string ENTIDAD_FEDERATIVA { get; set; }
        public string OPERACION { get; set; }
        public string SERVICIO { get; set; }
        public string DESCRIPCION_REPORTE { get; set; }
        public Nullable<decimal> IMPORTE_RECLAMADO { get; set; }
        public Nullable<decimal> IMPORTE_SOLUCION { get; set; }
        public string SUCURSAL_REGISTRO { get; set; }
        public string SUCURSAL_SOCIO { get; set; }
        public string TIPO_REPORTE { get; set; }
        public string CAUSA { get; set; }
    }
}
