//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UNE_USUARIOS_ASIGNADOS
    {
        public int contador { get; set; }
        public Nullable<int> folio { get; set; }
        public Nullable<int> numusuario { get; set; }
        public Nullable<int> responsable { get; set; }
        public Nullable<System.DateTime> fecha_asignacion { get; set; }
    
        public virtual TBL_UNE_REPORTE TBL_UNE_REPORTE { get; set; }
    }
}
