//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UNE_CONVERSION_LLAMADAS
    {
        public int ID_CONVERSION_LLAMADA { get; set; }
        public Nullable<decimal> INB_OUT_ID { get; set; }
        public string NUM_FOLIO { get; set; }
        public Nullable<System.DateTime> FECHA_CONVERSION { get; set; }
        public string RUTA { get; set; }
        public string NOMBRE_ARCHIVO { get; set; }
    }
}
