//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CALLCENTER_REGISTRO_REPORTE
    {
        public long id_registro_reporte { get; set; }
        public Nullable<long> numero_socio { get; set; }
        public string detalles_llamada { get; set; }
        public Nullable<System.DateTime> fecha_registro_reporte { get; set; }
        public Nullable<long> ID_SUPUESTOS_REPORTE { get; set; }
    }
}
