//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UNE_TIPO_ARCHIVO
    {
        public TBL_UNE_TIPO_ARCHIVO()
        {
            this.TBL_UNE_ARCHIVOS_ADJUNTOS = new HashSet<TBL_UNE_ARCHIVOS_ADJUNTOS>();
        }
    
        public int ID_TIPO_ARCHIVO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<TBL_UNE_ARCHIVOS_ADJUNTOS> TBL_UNE_ARCHIVOS_ADJUNTOS { get; set; }
    }
}
