//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BANCA_SOCIOS
    {
        public int id_socio { get; set; }
        public Nullable<int> id_persona { get; set; }
        public Nullable<int> numero_socio { get; set; }
        public string contrasena { get; set; }
        public Nullable<System.DateTime> fecha_alta_contrasena { get; set; }
        public string contrasena_temp { get; set; }
        public Nullable<System.DateTime> fecha_contrasena_temporal { get; set; }
        public Nullable<System.DateTime> fecha_alta_persona { get; set; }
        public Nullable<int> id_estatus_banca { get; set; }
        public Nullable<int> id_pregunta_secreta { get; set; }
        public string respuesta { get; set; }
        public Nullable<int> id_motivo_bloqueo { get; set; }
        public Nullable<bool> banca_activa { get; set; }
        public Nullable<System.DateTime> fecha_motivo_bloqueo { get; set; }
        public Nullable<int> id_imagen_antiphishing { get; set; }
        public Nullable<bool> vigencia_contrasena_temporal { get; set; }
        public Nullable<bool> viene_de_bloqueo { get; set; }
        public Nullable<int> id_ultima_sesion { get; set; }
        public Nullable<System.DateTime> fecha_ultima_sesion { get; set; }
        public Nullable<int> intentos_sesion { get; set; }
        public Nullable<int> intentos_respuesta { get; set; }
        public Nullable<System.DateTime> fecha_alta_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_de_desbloqueo { get; set; }
        public string contrasena_estado_cuenta { get; set; }
        public string descripcion_bloqueo { get; set; }
        public string descripcion_cancelacion { get; set; }
        public Nullable<System.DateTime> fecha_bloqueo_OTP { get; set; }
        public Nullable<System.DateTime> fecha_cancelacion { get; set; }
        public Nullable<long> codigo_contrasena { get; set; }
        public Nullable<System.DateTime> fecha_codigo_contrasena { get; set; }
        public Nullable<bool> recuperar_contrasena { get; set; }
        public Nullable<System.DateTime> fecha_alta_recuperar_contrasena { get; set; }
    }
}
