//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.Models
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextUneBD : DbContext
    {
        public ContextUneBD()
            : base("name=ContextUneBD")
        {
        }
        public ContextUneBD(String usuario, String contrasena) : base("name=ContextUneBD")
        {
            String conexion = "data source=" + ConfigurationSettings.AppSettings["servidorBD"] + ";initial catalog=HAPE;user id=" + usuario + ";password=" + contrasena + ";MultipleActiveResultSets=True;App=EntityFramework";
            Database.Connection.ConnectionString = conexion;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CMV_REC_DATA> CMV_REC_DATA { get; set; }
    }
}
