//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.conectaServicioSAS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conecta.mx")]
    public partial class faultBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultcode {
            get {
                return this.faultcodeField;
            }
            set {
                this.faultcodeField = value;
                this.RaisePropertyChanged("faultcode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.conecta.mx", ConfigurationName="conectaServicioSAS.ConectaServicesImpl")]
    public interface ConectaServicesImpl {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/ReasignacionRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/ReasignacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMV_CALLCENTER.conectaServicioSAS.faultBean), Action="http://www.conecta.mx/ConectaServicesImpl/Reasignacion/Fault/CustomException", Name="CustomException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMV_CALLCENTER.conectaServicioSAS.ReasignacionResponse Reasignacion(CMV_CALLCENTER.conectaServicioSAS.ReasignacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/ReasignacionRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/ReasignacionResponse")]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.ReasignacionResponse> ReasignacionAsync(CMV_CALLCENTER.conectaServicioSAS.ReasignacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/ObtenerUsuarioRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/ObtenerUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMV_CALLCENTER.conectaServicioSAS.faultBean), Action="http://www.conecta.mx/ConectaServicesImpl/ObtenerUsuario/Fault/CustomException", Name="CustomException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMV_CALLCENTER.conectaServicioSAS.ObtenerUsuarioResponse ObtenerUsuario(CMV_CALLCENTER.conectaServicioSAS.ObtenerUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/ObtenerUsuarioRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.ObtenerUsuarioResponse> ObtenerUsuarioAsync(CMV_CALLCENTER.conectaServicioSAS.ObtenerUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/RevocarTokenRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/RevocarTokenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMV_CALLCENTER.conectaServicioSAS.faultBean), Action="http://www.conecta.mx/ConectaServicesImpl/RevocarToken/Fault/CustomException", Name="CustomException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMV_CALLCENTER.conectaServicioSAS.RevocarTokenResponse RevocarToken(CMV_CALLCENTER.conectaServicioSAS.RevocarTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/RevocarTokenRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/RevocarTokenResponse")]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.RevocarTokenResponse> RevocarTokenAsync(CMV_CALLCENTER.conectaServicioSAS.RevocarTokenRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/EliminarUsuarioRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/EliminarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMV_CALLCENTER.conectaServicioSAS.faultBean), Action="http://www.conecta.mx/ConectaServicesImpl/EliminarUsuario/Fault/CustomException", Name="CustomException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMV_CALLCENTER.conectaServicioSAS.EliminarUsuarioResponse EliminarUsuario(CMV_CALLCENTER.conectaServicioSAS.EliminarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/EliminarUsuarioRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.EliminarUsuarioResponse> EliminarUsuarioAsync(CMV_CALLCENTER.conectaServicioSAS.EliminarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/AgregarUsuarioRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/AgregarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMV_CALLCENTER.conectaServicioSAS.faultBean), Action="http://www.conecta.mx/ConectaServicesImpl/AgregarUsuario/Fault/CustomException", Name="CustomException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMV_CALLCENTER.conectaServicioSAS.AgregarUsuarioResponse AgregarUsuario(CMV_CALLCENTER.conectaServicioSAS.AgregarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/AgregarUsuarioRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/AgregarUsuarioResponse")]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.AgregarUsuarioResponse> AgregarUsuarioAsync(CMV_CALLCENTER.conectaServicioSAS.AgregarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/AgregarAprovisionarUsuarioRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/AgregarAprovisionarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMV_CALLCENTER.conectaServicioSAS.faultBean), Action="http://www.conecta.mx/ConectaServicesImpl/AgregarAprovisionarUsuario/Fault/Custom" +
            "Exception", Name="CustomException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMV_CALLCENTER.conectaServicioSAS.AgregarAprovisionarUsuarioResponse AgregarAprovisionarUsuario(CMV_CALLCENTER.conectaServicioSAS.AgregarAprovisionarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/AgregarAprovisionarUsuarioRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/AgregarAprovisionarUsuarioResponse")]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.AgregarAprovisionarUsuarioResponse> AgregarAprovisionarUsuarioAsync(CMV_CALLCENTER.conectaServicioSAS.AgregarAprovisionarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/ActualizarUsuarioRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/ActualizarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMV_CALLCENTER.conectaServicioSAS.faultBean), Action="http://www.conecta.mx/ConectaServicesImpl/ActualizarUsuario/Fault/CustomException" +
            "", Name="CustomException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMV_CALLCENTER.conectaServicioSAS.ActualizarUsuarioResponse ActualizarUsuario(CMV_CALLCENTER.conectaServicioSAS.ActualizarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/ActualizarUsuarioRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/ActualizarUsuarioResponse")]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.ActualizarUsuarioResponse> ActualizarUsuarioAsync(CMV_CALLCENTER.conectaServicioSAS.ActualizarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/AprovisionarUsuariosRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/AprovisionarUsuariosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMV_CALLCENTER.conectaServicioSAS.faultBean), Action="http://www.conecta.mx/ConectaServicesImpl/AprovisionarUsuarios/Fault/CustomExcept" +
            "ion", Name="CustomException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMV_CALLCENTER.conectaServicioSAS.AprovisionarUsuariosResponse AprovisionarUsuarios(CMV_CALLCENTER.conectaServicioSAS.AprovisionarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/AprovisionarUsuariosRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/AprovisionarUsuariosResponse")]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.AprovisionarUsuariosResponse> AprovisionarUsuariosAsync(CMV_CALLCENTER.conectaServicioSAS.AprovisionarUsuariosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/ObtenerEstatusTokenRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/ObtenerEstatusTokenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMV_CALLCENTER.conectaServicioSAS.faultBean), Action="http://www.conecta.mx/ConectaServicesImpl/ObtenerEstatusToken/Fault/CustomExcepti" +
            "on", Name="CustomException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMV_CALLCENTER.conectaServicioSAS.ObtenerEstatusTokenResponse ObtenerEstatusToken(CMV_CALLCENTER.conectaServicioSAS.ObtenerEstatusTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/ConectaServicesImpl/ObtenerEstatusTokenRequest", ReplyAction="http://www.conecta.mx/ConectaServicesImpl/ObtenerEstatusTokenResponse")]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.ObtenerEstatusTokenResponse> ObtenerEstatusTokenAsync(CMV_CALLCENTER.conectaServicioSAS.ObtenerEstatusTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Reasignacion", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class ReasignacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        public ReasignacionRequest() {
        }
        
        public ReasignacionRequest(string UserName, string email) {
            this.UserName = UserName;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReasignacionResponse", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class ReasignacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ReasignacionResponse() {
        }
        
        public ReasignacionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cryptocard.com/blackshield/")]
    public partial class User : TimeRestrictedUser {
        
        private Group[] groupsField;
        
        private System.Nullable<int> preferredLanguageField;
        
        private string passwordSetDateField;
        
        private string passwordExpiryDateField;
        
        private int passwordAttemptCountField;
        
        private string userNameField;
        
        private string firstNameField;
        
        private string lastnameField;
        
        private string address1Field;
        
        private string cityField;
        
        private string stateField;
        
        private string countryField;
        
        private string zipField;
        
        private string emailField;
        
        private string telephoneField;
        
        private string countrycodeField;
        
        private string extensionField;
        
        private string mobileField;
        
        private string faxField;
        
        private bool lockedField;
        
        private string[] customAttributesField;
        
        private string unlockAtField;
        
        private string messageField;
        
        private bool tempPasswordEnabledField;
        
        private bool tempPasswordChangeReqField;
        
        private string containerNameField;
        
        private bool useExternalCredentialsField;
        
        private bool isAccountDormantField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Group[] Groups {
            get {
                return this.groupsField;
            }
            set {
                this.groupsField = value;
                this.RaisePropertyChanged("Groups");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> PreferredLanguage {
            get {
                return this.preferredLanguageField;
            }
            set {
                this.preferredLanguageField = value;
                this.RaisePropertyChanged("PreferredLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PasswordSetDate {
            get {
                return this.passwordSetDateField;
            }
            set {
                this.passwordSetDateField = value;
                this.RaisePropertyChanged("PasswordSetDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PasswordExpiryDate {
            get {
                return this.passwordExpiryDateField;
            }
            set {
                this.passwordExpiryDateField = value;
                this.RaisePropertyChanged("PasswordExpiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PasswordAttemptCount {
            get {
                return this.passwordAttemptCountField;
            }
            set {
                this.passwordAttemptCountField = value;
                this.RaisePropertyChanged("PasswordAttemptCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
                this.RaisePropertyChanged("Lastname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("Address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
                this.RaisePropertyChanged("Telephone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Countrycode {
            get {
                return this.countrycodeField;
            }
            set {
                this.countrycodeField = value;
                this.RaisePropertyChanged("Countrycode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("Extension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("Fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool Locked {
            get {
                return this.lockedField;
            }
            set {
                this.lockedField = value;
                this.RaisePropertyChanged("Locked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=20)]
        public string[] CustomAttributes {
            get {
                return this.customAttributesField;
            }
            set {
                this.customAttributesField = value;
                this.RaisePropertyChanged("CustomAttributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string UnlockAt {
            get {
                return this.unlockAtField;
            }
            set {
                this.unlockAtField = value;
                this.RaisePropertyChanged("UnlockAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public bool TempPasswordEnabled {
            get {
                return this.tempPasswordEnabledField;
            }
            set {
                this.tempPasswordEnabledField = value;
                this.RaisePropertyChanged("TempPasswordEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public bool TempPasswordChangeReq {
            get {
                return this.tempPasswordChangeReqField;
            }
            set {
                this.tempPasswordChangeReqField = value;
                this.RaisePropertyChanged("TempPasswordChangeReq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string ContainerName {
            get {
                return this.containerNameField;
            }
            set {
                this.containerNameField = value;
                this.RaisePropertyChanged("ContainerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public bool UseExternalCredentials {
            get {
                return this.useExternalCredentialsField;
            }
            set {
                this.useExternalCredentialsField = value;
                this.RaisePropertyChanged("UseExternalCredentials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public bool IsAccountDormant {
            get {
                return this.isAccountDormantField;
            }
            set {
                this.isAccountDormantField = value;
                this.RaisePropertyChanged("IsAccountDormant");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cryptocard.com/blackshield/")]
    public partial class Group : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string groupNameField;
        
        private string descriptionField;
        
        private bool readOnlyField;
        
        private bool emptyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("GroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool ReadOnly {
            get {
                return this.readOnlyField;
            }
            set {
                this.readOnlyField = value;
                this.RaisePropertyChanged("ReadOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool Empty {
            get {
                return this.emptyField;
            }
            set {
                this.emptyField = value;
                this.RaisePropertyChanged("Empty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cryptocard.com/blackshield/")]
    public abstract partial class TimeRestrictedUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool restrictionsEnabledField;
        
        private string startDateField;
        
        private string endDateField;
        
        private string startTimeField;
        
        private string endTimeField;
        
        private WeekRestrictions restrictedDaysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool RestrictionsEnabled {
            get {
                return this.restrictionsEnabledField;
            }
            set {
                this.restrictionsEnabledField = value;
                this.RaisePropertyChanged("RestrictionsEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("StartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("EndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public WeekRestrictions RestrictedDays {
            get {
                return this.restrictedDaysField;
            }
            set {
                this.restrictedDaysField = value;
                this.RaisePropertyChanged("RestrictedDays");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cryptocard.com/blackshield/")]
    public partial class WeekRestrictions : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUsuario", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class ObtenerUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserName;
        
        public ObtenerUsuarioRequest() {
        }
        
        public ObtenerUsuarioRequest(string UserName) {
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUsuarioResponse", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class ObtenerUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CMV_CALLCENTER.conectaServicioSAS.User @return;
        
        public ObtenerUsuarioResponse() {
        }
        
        public ObtenerUsuarioResponse(CMV_CALLCENTER.conectaServicioSAS.User @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RevocarToken", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class RevocarTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserName;
        
        public RevocarTokenRequest() {
        }
        
        public RevocarTokenRequest(string UserName) {
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RevocarTokenResponse", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class RevocarTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public RevocarTokenResponse() {
        }
        
        public RevocarTokenResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarUsuario", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class EliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserName;
        
        public EliminarUsuarioRequest() {
        }
        
        public EliminarUsuarioRequest(string UserName) {
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarUsuarioResponse", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class EliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public EliminarUsuarioResponse() {
        }
        
        public EliminarUsuarioResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conecta.mx")]
    public partial class UserCustom : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string firstNameField;
        
        private string lastnameField;
        
        private string emailField;
        
        private string mobileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
                this.RaisePropertyChanged("Lastname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarUsuario", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class AgregarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CMV_CALLCENTER.conectaServicioSAS.UserCustom usuario;
        
        public AgregarUsuarioRequest() {
        }
        
        public AgregarUsuarioRequest(CMV_CALLCENTER.conectaServicioSAS.UserCustom usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarUsuarioResponse", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class AgregarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public AgregarUsuarioResponse() {
        }
        
        public AgregarUsuarioResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarAprovisionarUsuario", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class AgregarAprovisionarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CMV_CALLCENTER.conectaServicioSAS.UserCustom usuario;
        
        public AgregarAprovisionarUsuarioRequest() {
        }
        
        public AgregarAprovisionarUsuarioRequest(CMV_CALLCENTER.conectaServicioSAS.UserCustom usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarAprovisionarUsuarioResponse", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class AgregarAprovisionarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public AgregarAprovisionarUsuarioResponse() {
        }
        
        public AgregarAprovisionarUsuarioResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conecta.mx")]
    public partial class UserUpdatingCustom : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarUsuario", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class ActualizarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CMV_CALLCENTER.conectaServicioSAS.UserUpdatingCustom Usuario;
        
        public ActualizarUsuarioRequest() {
        }
        
        public ActualizarUsuarioRequest(string UserName, CMV_CALLCENTER.conectaServicioSAS.UserUpdatingCustom Usuario) {
            this.UserName = UserName;
            this.Usuario = Usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarUsuarioResponse", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class ActualizarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ActualizarUsuarioResponse() {
        }
        
        public ActualizarUsuarioResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AprovisionarUsuarios", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class AprovisionarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://www.cryptocard.com/blackshield/")]
        public string[] usuarios;
        
        public AprovisionarUsuariosRequest() {
        }
        
        public AprovisionarUsuariosRequest(string[] usuarios) {
            this.usuarios = usuarios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AprovisionarUsuariosResponse", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class AprovisionarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public AprovisionarUsuariosResponse() {
        }
        
        public AprovisionarUsuariosResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerEstatusToken", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class ObtenerEstatusTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserName;
        
        public ObtenerEstatusTokenRequest() {
        }
        
        public ObtenerEstatusTokenRequest(string UserName) {
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerEstatusTokenResponse", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class ObtenerEstatusTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ObtenerEstatusTokenResponse() {
        }
        
        public ObtenerEstatusTokenResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConectaServicesImplChannel : CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConectaServicesImplClient : System.ServiceModel.ClientBase<CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl>, CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl {
        
        public ConectaServicesImplClient() {
        }
        
        public ConectaServicesImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConectaServicesImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConectaServicesImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConectaServicesImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMV_CALLCENTER.conectaServicioSAS.ReasignacionResponse CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.Reasignacion(CMV_CALLCENTER.conectaServicioSAS.ReasignacionRequest request) {
            return base.Channel.Reasignacion(request);
        }
        
        public string Reasignacion(string UserName, string email) {
            CMV_CALLCENTER.conectaServicioSAS.ReasignacionRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.ReasignacionRequest();
            inValue.UserName = UserName;
            inValue.email = email;
            CMV_CALLCENTER.conectaServicioSAS.ReasignacionResponse retVal = ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).Reasignacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.ReasignacionResponse> CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.ReasignacionAsync(CMV_CALLCENTER.conectaServicioSAS.ReasignacionRequest request) {
            return base.Channel.ReasignacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.ReasignacionResponse> ReasignacionAsync(string UserName, string email) {
            CMV_CALLCENTER.conectaServicioSAS.ReasignacionRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.ReasignacionRequest();
            inValue.UserName = UserName;
            inValue.email = email;
            return ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).ReasignacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMV_CALLCENTER.conectaServicioSAS.ObtenerUsuarioResponse CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.ObtenerUsuario(CMV_CALLCENTER.conectaServicioSAS.ObtenerUsuarioRequest request) {
            return base.Channel.ObtenerUsuario(request);
        }
        
        public CMV_CALLCENTER.conectaServicioSAS.User ObtenerUsuario(string UserName) {
            CMV_CALLCENTER.conectaServicioSAS.ObtenerUsuarioRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.ObtenerUsuarioRequest();
            inValue.UserName = UserName;
            CMV_CALLCENTER.conectaServicioSAS.ObtenerUsuarioResponse retVal = ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).ObtenerUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.ObtenerUsuarioResponse> CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.ObtenerUsuarioAsync(CMV_CALLCENTER.conectaServicioSAS.ObtenerUsuarioRequest request) {
            return base.Channel.ObtenerUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.ObtenerUsuarioResponse> ObtenerUsuarioAsync(string UserName) {
            CMV_CALLCENTER.conectaServicioSAS.ObtenerUsuarioRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.ObtenerUsuarioRequest();
            inValue.UserName = UserName;
            return ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).ObtenerUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMV_CALLCENTER.conectaServicioSAS.RevocarTokenResponse CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.RevocarToken(CMV_CALLCENTER.conectaServicioSAS.RevocarTokenRequest request) {
            return base.Channel.RevocarToken(request);
        }
        
        public string RevocarToken(string UserName) {
            CMV_CALLCENTER.conectaServicioSAS.RevocarTokenRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.RevocarTokenRequest();
            inValue.UserName = UserName;
            CMV_CALLCENTER.conectaServicioSAS.RevocarTokenResponse retVal = ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).RevocarToken(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.RevocarTokenResponse> CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.RevocarTokenAsync(CMV_CALLCENTER.conectaServicioSAS.RevocarTokenRequest request) {
            return base.Channel.RevocarTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.RevocarTokenResponse> RevocarTokenAsync(string UserName) {
            CMV_CALLCENTER.conectaServicioSAS.RevocarTokenRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.RevocarTokenRequest();
            inValue.UserName = UserName;
            return ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).RevocarTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMV_CALLCENTER.conectaServicioSAS.EliminarUsuarioResponse CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.EliminarUsuario(CMV_CALLCENTER.conectaServicioSAS.EliminarUsuarioRequest request) {
            return base.Channel.EliminarUsuario(request);
        }
        
        public string EliminarUsuario(string UserName) {
            CMV_CALLCENTER.conectaServicioSAS.EliminarUsuarioRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.EliminarUsuarioRequest();
            inValue.UserName = UserName;
            CMV_CALLCENTER.conectaServicioSAS.EliminarUsuarioResponse retVal = ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).EliminarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.EliminarUsuarioResponse> CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.EliminarUsuarioAsync(CMV_CALLCENTER.conectaServicioSAS.EliminarUsuarioRequest request) {
            return base.Channel.EliminarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.EliminarUsuarioResponse> EliminarUsuarioAsync(string UserName) {
            CMV_CALLCENTER.conectaServicioSAS.EliminarUsuarioRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.EliminarUsuarioRequest();
            inValue.UserName = UserName;
            return ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).EliminarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMV_CALLCENTER.conectaServicioSAS.AgregarUsuarioResponse CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.AgregarUsuario(CMV_CALLCENTER.conectaServicioSAS.AgregarUsuarioRequest request) {
            return base.Channel.AgregarUsuario(request);
        }
        
        public string AgregarUsuario(CMV_CALLCENTER.conectaServicioSAS.UserCustom usuario) {
            CMV_CALLCENTER.conectaServicioSAS.AgregarUsuarioRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.AgregarUsuarioRequest();
            inValue.usuario = usuario;
            CMV_CALLCENTER.conectaServicioSAS.AgregarUsuarioResponse retVal = ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).AgregarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.AgregarUsuarioResponse> CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.AgregarUsuarioAsync(CMV_CALLCENTER.conectaServicioSAS.AgregarUsuarioRequest request) {
            return base.Channel.AgregarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.AgregarUsuarioResponse> AgregarUsuarioAsync(CMV_CALLCENTER.conectaServicioSAS.UserCustom usuario) {
            CMV_CALLCENTER.conectaServicioSAS.AgregarUsuarioRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.AgregarUsuarioRequest();
            inValue.usuario = usuario;
            return ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).AgregarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMV_CALLCENTER.conectaServicioSAS.AgregarAprovisionarUsuarioResponse CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.AgregarAprovisionarUsuario(CMV_CALLCENTER.conectaServicioSAS.AgregarAprovisionarUsuarioRequest request) {
            return base.Channel.AgregarAprovisionarUsuario(request);
        }
        
        public string AgregarAprovisionarUsuario(CMV_CALLCENTER.conectaServicioSAS.UserCustom usuario) {
            CMV_CALLCENTER.conectaServicioSAS.AgregarAprovisionarUsuarioRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.AgregarAprovisionarUsuarioRequest();
            inValue.usuario = usuario;
            CMV_CALLCENTER.conectaServicioSAS.AgregarAprovisionarUsuarioResponse retVal = ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).AgregarAprovisionarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.AgregarAprovisionarUsuarioResponse> CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.AgregarAprovisionarUsuarioAsync(CMV_CALLCENTER.conectaServicioSAS.AgregarAprovisionarUsuarioRequest request) {
            return base.Channel.AgregarAprovisionarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.AgregarAprovisionarUsuarioResponse> AgregarAprovisionarUsuarioAsync(CMV_CALLCENTER.conectaServicioSAS.UserCustom usuario) {
            CMV_CALLCENTER.conectaServicioSAS.AgregarAprovisionarUsuarioRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.AgregarAprovisionarUsuarioRequest();
            inValue.usuario = usuario;
            return ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).AgregarAprovisionarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMV_CALLCENTER.conectaServicioSAS.ActualizarUsuarioResponse CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.ActualizarUsuario(CMV_CALLCENTER.conectaServicioSAS.ActualizarUsuarioRequest request) {
            return base.Channel.ActualizarUsuario(request);
        }
        
        public string ActualizarUsuario(string UserName, CMV_CALLCENTER.conectaServicioSAS.UserUpdatingCustom Usuario) {
            CMV_CALLCENTER.conectaServicioSAS.ActualizarUsuarioRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.ActualizarUsuarioRequest();
            inValue.UserName = UserName;
            inValue.Usuario = Usuario;
            CMV_CALLCENTER.conectaServicioSAS.ActualizarUsuarioResponse retVal = ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).ActualizarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.ActualizarUsuarioResponse> CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.ActualizarUsuarioAsync(CMV_CALLCENTER.conectaServicioSAS.ActualizarUsuarioRequest request) {
            return base.Channel.ActualizarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.ActualizarUsuarioResponse> ActualizarUsuarioAsync(string UserName, CMV_CALLCENTER.conectaServicioSAS.UserUpdatingCustom Usuario) {
            CMV_CALLCENTER.conectaServicioSAS.ActualizarUsuarioRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.ActualizarUsuarioRequest();
            inValue.UserName = UserName;
            inValue.Usuario = Usuario;
            return ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).ActualizarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMV_CALLCENTER.conectaServicioSAS.AprovisionarUsuariosResponse CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.AprovisionarUsuarios(CMV_CALLCENTER.conectaServicioSAS.AprovisionarUsuariosRequest request) {
            return base.Channel.AprovisionarUsuarios(request);
        }
        
        public string[] AprovisionarUsuarios(string[] usuarios) {
            CMV_CALLCENTER.conectaServicioSAS.AprovisionarUsuariosRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.AprovisionarUsuariosRequest();
            inValue.usuarios = usuarios;
            CMV_CALLCENTER.conectaServicioSAS.AprovisionarUsuariosResponse retVal = ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).AprovisionarUsuarios(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.AprovisionarUsuariosResponse> CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.AprovisionarUsuariosAsync(CMV_CALLCENTER.conectaServicioSAS.AprovisionarUsuariosRequest request) {
            return base.Channel.AprovisionarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.AprovisionarUsuariosResponse> AprovisionarUsuariosAsync(string[] usuarios) {
            CMV_CALLCENTER.conectaServicioSAS.AprovisionarUsuariosRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.AprovisionarUsuariosRequest();
            inValue.usuarios = usuarios;
            return ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).AprovisionarUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMV_CALLCENTER.conectaServicioSAS.ObtenerEstatusTokenResponse CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.ObtenerEstatusToken(CMV_CALLCENTER.conectaServicioSAS.ObtenerEstatusTokenRequest request) {
            return base.Channel.ObtenerEstatusToken(request);
        }
        
        public string ObtenerEstatusToken(string UserName) {
            CMV_CALLCENTER.conectaServicioSAS.ObtenerEstatusTokenRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.ObtenerEstatusTokenRequest();
            inValue.UserName = UserName;
            CMV_CALLCENTER.conectaServicioSAS.ObtenerEstatusTokenResponse retVal = ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).ObtenerEstatusToken(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.ObtenerEstatusTokenResponse> CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl.ObtenerEstatusTokenAsync(CMV_CALLCENTER.conectaServicioSAS.ObtenerEstatusTokenRequest request) {
            return base.Channel.ObtenerEstatusTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioSAS.ObtenerEstatusTokenResponse> ObtenerEstatusTokenAsync(string UserName) {
            CMV_CALLCENTER.conectaServicioSAS.ObtenerEstatusTokenRequest inValue = new CMV_CALLCENTER.conectaServicioSAS.ObtenerEstatusTokenRequest();
            inValue.UserName = UserName;
            return ((CMV_CALLCENTER.conectaServicioSAS.ConectaServicesImpl)(this)).ObtenerEstatusTokenAsync(inValue);
        }
    }
}
