//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMV_CALLCENTER.conectaServicioAutenticador {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.conecta.mx")]
    public partial class faultBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultcode {
            get {
                return this.faultcodeField;
            }
            set {
                this.faultcodeField = value;
                this.RaisePropertyChanged("faultcode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.conecta.mx", ConfigurationName="conectaServicioAutenticador.CRYPTOCardImpl")]
    public interface CRYPTOCardImpl {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/CRYPTOCardImpl/AutenticarRequest", ReplyAction="http://www.conecta.mx/CRYPTOCardImpl/AutenticarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMV_CALLCENTER.conectaServicioAutenticador.faultBean), Action="http://www.conecta.mx/CRYPTOCardImpl/Autenticar/Fault/CustomException", Name="CustomException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMV_CALLCENTER.conectaServicioAutenticador.AutenticarResponse Autenticar(CMV_CALLCENTER.conectaServicioAutenticador.AutenticarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.conecta.mx/CRYPTOCardImpl/AutenticarRequest", ReplyAction="http://www.conecta.mx/CRYPTOCardImpl/AutenticarResponse")]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioAutenticador.AutenticarResponse> AutenticarAsync(CMV_CALLCENTER.conectaServicioAutenticador.AutenticarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Autenticar", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class AutenticarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pin;
        
        public AutenticarRequest() {
        }
        
        public AutenticarRequest(string usuario, string pin) {
            this.usuario = usuario;
            this.pin = pin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticarResponse", WrapperNamespace="http://www.conecta.mx", IsWrapped=true)]
    public partial class AutenticarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.conecta.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public AutenticarResponse() {
        }
        
        public AutenticarResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CRYPTOCardImplChannel : CMV_CALLCENTER.conectaServicioAutenticador.CRYPTOCardImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRYPTOCardImplClient : System.ServiceModel.ClientBase<CMV_CALLCENTER.conectaServicioAutenticador.CRYPTOCardImpl>, CMV_CALLCENTER.conectaServicioAutenticador.CRYPTOCardImpl {
        
        public CRYPTOCardImplClient() {
        }
        
        public CRYPTOCardImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRYPTOCardImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRYPTOCardImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRYPTOCardImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMV_CALLCENTER.conectaServicioAutenticador.AutenticarResponse CMV_CALLCENTER.conectaServicioAutenticador.CRYPTOCardImpl.Autenticar(CMV_CALLCENTER.conectaServicioAutenticador.AutenticarRequest request) {
            return base.Channel.Autenticar(request);
        }
        
        public string Autenticar(string usuario, string pin) {
            CMV_CALLCENTER.conectaServicioAutenticador.AutenticarRequest inValue = new CMV_CALLCENTER.conectaServicioAutenticador.AutenticarRequest();
            inValue.usuario = usuario;
            inValue.pin = pin;
            CMV_CALLCENTER.conectaServicioAutenticador.AutenticarResponse retVal = ((CMV_CALLCENTER.conectaServicioAutenticador.CRYPTOCardImpl)(this)).Autenticar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioAutenticador.AutenticarResponse> CMV_CALLCENTER.conectaServicioAutenticador.CRYPTOCardImpl.AutenticarAsync(CMV_CALLCENTER.conectaServicioAutenticador.AutenticarRequest request) {
            return base.Channel.AutenticarAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMV_CALLCENTER.conectaServicioAutenticador.AutenticarResponse> AutenticarAsync(string usuario, string pin) {
            CMV_CALLCENTER.conectaServicioAutenticador.AutenticarRequest inValue = new CMV_CALLCENTER.conectaServicioAutenticador.AutenticarRequest();
            inValue.usuario = usuario;
            inValue.pin = pin;
            return ((CMV_CALLCENTER.conectaServicioAutenticador.CRYPTOCardImpl)(this)).AutenticarAsync(inValue);
        }
    }
}
